AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: EECAR - B2B Platform for Used EV Parts Trading

Globals:
  Function:
    Runtime: nodejs20.x
    MemorySize: 512  # Cost-optimized, increase if needed
    Timeout: 30
    Environment:
      Variables:
        PARTS_TABLE_NAME: !Ref PartsTable
        VECTORS_BUCKET_NAME: !Ref VectorsBucket
        DOCUMENTS_BUCKET_NAME: !Ref DocumentsBucket
        SNS_TOPIC_ARN: !Ref NotificationTopic
        BEDROCK_MODEL_ID: anthropic.claude-3-haiku-20240307-v1:0  # Cost-optimized for text generation (Titan is for embeddings)
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
      AllowOrigin: "'*'"

Resources:
  # Lambda Layer for shared utilities
  EECARUtilsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: eecar-utils-layer
      Description: Shared utilities for EECAR Lambda functions (DynamoDB, S3, Bedrock)
      ContentUri: ../backend/dist/layer/nodejs/
      CompatibleRuntimes:
        - nodejs20.x
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: nodejs20.x

  # API Gateway
  EECARApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Description: EECAR API Gateway
      TracingEnabled: false  # Cost optimization: disable X-Ray for now

  # Lambda Functions
  VectorSearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../backend/dist/functions/vector-search/
      Handler: index.handler
      Description: AI-powered vector search for parts matching
      Layers:
        - !Ref EECARUtilsLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PartsTable
        - S3ReadPolicy:
            BucketName: !Ref VectorsBucket
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
              Resource: 'arn:aws:bedrock:us-east-1::foundation-model/*'
      Events:
        Search:
          Type: Api
          Properties:
            RestApiId: !Ref EECARApi
            Path: /api/search
            Method: POST

  PartRegistrationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../backend/dist/functions/part-registration/
      Handler: index.handler
      Description: Register new parts and generate embeddings
      MemorySize: 1024  # Higher memory for embedding generation
      Timeout: 60  # Longer timeout for AI processing
      Layers:
        - !Ref EECARUtilsLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PartsTable
        - S3CrudPolicy:
            BucketName: !Ref VectorsBucket
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
              Resource: 'arn:aws:bedrock:us-east-1::foundation-model/*'
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: '*'
      Environment:
        Variables:
          COMPLIANCE_FUNCTION_NAME: !Ref ComplianceCheckFunction
      Events:
        RegisterPart:
          Type: Api
          Properties:
            RestApiId: !Ref EECARApi
            Path: /api/parts
            Method: POST

  ComplianceCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../backend/dist/functions/compliance-check/
      Handler: index.handler
      Description: Validate parts against compliance rules (invoked by part registration)
      Layers:
        - !Ref EECARUtilsLayer
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref DocumentsBucket
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt NotificationTopic.TopicName
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
              Resource: 'arn:aws:bedrock:us-east-1::foundation-model/*'

  GetPartsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../backend/dist/functions/get-parts/
      Handler: index.handler
      Description: Retrieve parts information
      Layers:
        - !Ref EECARUtilsLayer
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref PartsTable
      Events:
        GetPart:
          Type: Api
          Properties:
            RestApiId: !Ref EECARApi
            Path: /api/parts/{id}
            Method: GET
        ListParts:
          Type: Api
          Properties:
            RestApiId: !Ref EECARApi
            Path: /api/parts
            Method: GET

  WatchPartFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../backend/dist/functions/watch-part/
      Handler: index.handler
      Description: Register alerts for desired parts
      Layers:
        - !Ref EECARUtilsLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PartsTable
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt NotificationTopic.TopicName
      Events:
        CreateWatch:
          Type: Api
          Properties:
            RestApiId: !Ref EECARApi
            Path: /api/watch
            Method: POST

  ProposalFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../backend/dist/functions/proposal/
      Handler: index.handler
      Description: Handle B2B contract proposals
      Layers:
        - !Ref EECARUtilsLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PartsTable
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt NotificationTopic.TopicName
      Events:
        CreateProposal:
          Type: Api
          Properties:
            RestApiId: !Ref EECARApi
            Path: /api/proposals
            Method: POST
        GetProposals:
          Type: Api
          Properties:
            RestApiId: !Ref EECARApi
            Path: /api/proposals
            Method: GET

  SyntheticDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../backend/dist/functions/synthetic-data/
      Handler: index.handler
      Description: Generate synthetic part data using MCP-style tools
      MemorySize: 1024
      Timeout: 120  # Longer for bulk generation
      Layers:
        - !Ref EECARUtilsLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PartsTable
        - S3CrudPolicy:
            BucketName: !Ref VectorsBucket
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
              Resource: 'arn:aws:bedrock:us-east-1::foundation-model/*'
      Events:
        GenerateData:
          Type: Api
          Properties:
            RestApiId: !Ref EECARApi
            Path: /api/synthetic
            Method: POST

  BatteryHealthAssessmentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../backend/dist/functions/battery-health-assessment/
      Handler: index.handler
      Description: Battery SOH-based advanced search with reuse/recycle assessment
      Layers:
        - !Ref EECARUtilsLayer
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref PartsTable
      Events:
        BatteryHealth:
          Type: Api
          Properties:
            RestApiId: !Ref EECARApi
            Path: /api/battery-health
            Method: POST

  MaterialPropertySearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../backend/dist/functions/material-property-search/
      Handler: index.handler
      Description: Material property-based search for aluminum alloys and specifications
      Layers:
        - !Ref EECARUtilsLayer
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref PartsTable
      Events:
        MaterialSearch:
          Type: Api
          Properties:
            RestApiId: !Ref EECARApi
            Path: /api/material-search
            Method: POST

  # DynamoDB Table (Single-table design for cost optimization)
  PartsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: eecar-parts-table
      BillingMode: PAY_PER_REQUEST  # On-demand pricing for low traffic
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: TTL
        Enabled: true
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false  # Cost optimization

  # S3 Buckets
  VectorsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'eecar-vectors-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  DocumentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'eecar-documents-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # SNS Topic for Notifications
  NotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: eecar-notifications
      DisplayName: EECAR Platform Notifications

  # Email Subscription for Notifications
  NotificationEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      TopicArn: !Ref NotificationTopic
      Endpoint: inha2025vip@gmail.com

  # CloudWatch Log Groups (with retention for cost control)
  VectorSearchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${VectorSearchFunction}'
      RetentionInDays: 7  # Cost optimization: short retention

  PartRegistrationLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${PartRegistrationFunction}'
      RetentionInDays: 7

  ComplianceCheckLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ComplianceCheckFunction}'
      RetentionInDays: 7

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${EECARApi}.execute-api.${AWS::Region}.amazonaws.com/prod'
    Export:
      Name: !Sub '${AWS::StackName}-ApiEndpoint'

  PartsTableName:
    Description: DynamoDB table name
    Value: !Ref PartsTable
    Export:
      Name: !Sub '${AWS::StackName}-PartsTable'

  VectorsBucketName:
    Description: S3 bucket for vector embeddings
    Value: !Ref VectorsBucket
    Export:
      Name: !Sub '${AWS::StackName}-VectorsBucket'

  DocumentsBucketName:
    Description: S3 bucket for compliance documents
    Value: !Ref DocumentsBucket
    Export:
      Name: !Sub '${AWS::StackName}-DocumentsBucket'

  NotificationTopicArn:
    Description: SNS topic ARN for notifications
    Value: !Ref NotificationTopic
    Export:
      Name: !Sub '${AWS::StackName}-NotificationTopic'
